apiVersion: v1
kind: Service
metadata:
  name: {{ include "skquad.apiServerName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "skquad.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-server
spec:
  type: ClusterIP
  selector:
    {{- include "skquad.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api-server
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
