apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "skquad.apiServerName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "skquad.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-server
rules:
  - apiGroups:
      - skquad.io
    resources:
      - squads
      - agents
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - update
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "skquad.apiServerName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "skquad.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "skquad.apiServerName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "skquad.apiServerName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "skquad.apiServerName" . }}-agent-secrets
  labels:
    {{- include "skquad.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-server
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - create
      - patch
      - update
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "skquad.apiServerName" . }}-agent-secrets
  labels:
    {{- include "skquad.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-server
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "skquad.apiServerName" . }}-agent-secrets
subjects:
  - kind: ServiceAccount
    name: {{ include "skquad.apiServerName" . }}
    namespace: {{ .Release.Namespace }}
