apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "skquad.operatorName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "skquad.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
