{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "skquad.postgresName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "skquad.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
type: Opaque
stringData:
  database: {{ .Values.postgres.database | quote }}
  username: {{ .Values.postgres.user | quote }}
  password: {{ .Values.postgres.password | quote }}
  database-url: {{ printf "postgres://%s:%s@%s:5432/%s?sslmode=disable" .Values.postgres.user .Values.postgres.password (include "skquad.postgresName" .) .Values.postgres.database | quote }}
{{- end }}
